### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/PyMatcha#466]
- [x] Ask David to create team
- [ ] Prepare env files / variables for eval
- [ ] Ask 2 people to evaluate our matcha via correction sheet / simply check it out
- [ ] Do final evaluation each of us on our own before handing it in

Jules:

- [x] Your application must not have any errors, warning or notice, nor server-side nor client-side.
- [x] Your whole app must be compatible at least with Firefox (>= 41) and Chrome (>= 46).
- [x] Your website must be usable on a mobile phone and keep an acceptable layout on small resolutions.
- [x] ◦ To be able to alter a SQL request.
- [x] ◦ To be able to upload unwanted content.
- [x] After the registration, an e-mail with an unique link must be sent to the registered user to verify his account.
- [x] Create manually man and woman with similar interests, so that while evaluating we can showcase chat etc. easy
- [x] Test expired access & refresh tokens

Lauris:

- [x] Your application must not have any errors, warning or notice, nor server-side nor client-side.
- [x] Your whole app must be compatible at least with Firefox (>= 41) and Chrome (>= 46).
- [x] Your website must be usable on a mobile phone and keep an acceptable layout on small resolutions.
- [x] ◦ To be able to alter a SQL request.
- [x] ◦ To be able to upload unwanted content.
- [x] After the registration, an e-mail with an unique link must be sent to the registered user to verify his account.
- [x] Create manually man and woman with similar interests, so that while evaluating we can showcase chat etc. easy
- [x] Test expired access & refresh tokens

**Comment by Seluj78** [comment]
<img width="1231" alt="Screenshot 2020-11-18 at 17 23 56" src="https://user-images.githubusercontent.com/4641317/99557327-da6e7b80-29c2-11eb-8a1e-b51d04b114db.png">
@supalarry a css to fix after trying to upload txt file

**Comment by Seluj78** [comment]
also https://flaviocopes.com/how-to-accept-images-file-input/
